name: lista_supermercado
description: "SmartCart - Lista de compras inteligente con voz."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_tts: ^3.8.5
  speech_to_text: ^7.0.0
  provider: ^6.1.2
  sqflite: ^2.3.0
  path_provider: ^2.1.3
  path: ^1.9.0
  shared_preferences: ^2.3.5
  share_plus: ^10.1.3
  url_launcher: ^6.3.1
  simple_barcode_scanner: ^0.6.0
  http: ^1.6.0
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff" # Fondo blanco para Android
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/foto_luis.jpg
    - assets/icon.png